[build-system]
requires = ["setuptools >= 77.0.3", "wheel", "setuptools-git-versioning"]
build-backend = "setuptools.build_meta"
[tool.setuptools-git-versioning]
enabled = true

[project]
name = "hebb"
authors = [
    { name = "Andrea Negri", email = "anegri@us.es" }
]
readme = "README.md"
description = "Halo Extreme Block Bootstrap package to estimate the largest halo mass given the field of view and redshift depth of a survey"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "BSD-3-clause"
license-files = ["LICEN[CS]E*"]


requires-python = ">=3.10"
dependencies = [
    "numpy",
    "astropy",
    "scipy",
    "h5py>=3.2.0",
    "numba",
    "scipy",
    "matplotlib",
    "mpi4py",
    ]

dynamic = ["version"]

[project.optional-dependencies]

[project.urls]
Homepage = "https://github.com/NegriAndrea/hebb"
Issues = "https://github.com/NegriAndrea/hebb/issues"

[project.scripts]
hebb = "hebb.hebb_cli:hebb_CLI"
hebb-tr = "hebb.hebb_cli:hebb_trace_CLI"
